name: Publish to GitHub Releases

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17' # 指定所需的 Java 版本

    - name: Build with Maven
      run: mvn clean install

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/*.jar # 根据实际需要指定构建产物的路径
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Release URL
      run: echo "Release URL: ${{ steps.create_release.outputs.html_url }}"
